### ISSUE TITLE
Error if some files are ESM

### ISSUE THREAD

**Issue by kuraga** [calvinmetcalf/rollup-plugin-node-globals#20]
Minimal example: 
[rollup-issue2.zip](https://github.com/calvinmetcalf/rollup-plugin-node-globals/files/2495640/rollup-issue2.zip), then `node build.js`.

Result:
```
Error: 'default' is not exported by another.js
    at error (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:3460:30)
    at Module.error (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:13358:9)
    at handleMissingExport (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:13048:21)
    at Module.traceVariable (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:13466:17)
    at ModuleScope.findVariable (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:12713:29)
    at Identifier$$1.bind (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:10111:40)
    at CallExpression.NodeBase.bind (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:9179:31)
    at CallExpression.bind (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:10224:31)
    at ExpressionStatement$$1.NodeBase.bind (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:9183:23)
    at Program.NodeBase.bind (/home/sasha/rollup_issue2/node_modules/rollup/dist/rollup.js:9179:31)
```

Note: see `another.js`.

We can have the same error without any "Node globals" such as `process`: just remove `rollup-plugin-commonjs` Rollup plugin from building and replace `process` by `'something'`.

/cc @calvinmetcalf

**Comment by kuraga** [comment]
@calvinmetcalf , ping

**Comment by kuraga** [comment]
@calvinmetcalf , any thoughts?

**Comment by kuraga** [comment]
@calvinmetcalf , ping
