### ISSUE TITLE
Error: "Illegal reassignment to import 'process'"

### ISSUE THREAD

**Issue by TheBosZ** [calvinmetcalf/rollup-plugin-node-globals#5]
I'm trying to use the AWS SDK and I'm getting the following error:

```
Illegal reassignment to import 'process'
Error: Illegal reassignment to import 'process'
    at error (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\utils\error.js:2:14)
    at disallowIllegalReassignment (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\nodes\shared\disallowIllegalReassignment.js:20:4)
    at AssignmentExpression.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\nodes\AssignmentExpression.js:12:3)
    at C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:34
    at ExpressionStatement.eachChild (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:21:5)
    at ExpressionStatement.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:8)
    at BlockStatement.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\nodes\BlockStatement.js:8:9)
    at C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:34
    at IfStatement.eachChild (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:21:5)
    at IfStatement.bind (C:\Projects\cloud-iris-web-frontend\node_modules\rollup\src\ast\Node.js:6:8)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
```

Here is my rollup.config.js:

```
import typescript from 'rollup-plugin-typescript';
import babel   from 'rollup-plugin-babel'
import replace from 'rollup-plugin-replace'
import uglify from 'rollup-plugin-uglify';
import sass from 'rollup-plugin-sass';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import json from 'rollup-plugin-json';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';

export default {
	entry: './src/index.tsx',
	dest: './dist/app.min.js',
	format: 'iife',
	sourceMap: './dist/app.min.js.map',
	moduleName: 'MyBundle',
	plugins: [
		builtins(),
		sass({
			insert: true,
			options: {
				outputStyle: 'compressed'
			}
		}),
		replace({
			'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
		}),
		typescript(),


		commonjs({
			ignoreGlobal: true,
			namedExports: {
				'react': [
					'PropTypes',
					'createElement',
					'cloneElement',
					'Component'
				],
				'node_modules/react-dom/index.js': [
					'render'
				]
			}
		}),

		resolve({
			jsnext: true,
			main: true,
			browser: true,
			preferBuiltins: true
		}),

		babel({
			exclude: 'node_modules/**',
			compact: false
		}),
		globals(),
		json(),

		(process.env.NODE_ENV === 'production' && uglify())
	]
}
```

And my package.json:

```
{
  "name": "Iris-FE",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "postinstall": "typings install",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js",
    "postinstall": "npm run typings install",
    "build": "tslint --project ./tsconfig.json && rollup -c",
  },
  "dependencies": {
    "body-parser": "^1.4.3",
    "debug": "^2.2.0",
    "express": "^4.4.5"
  },
  "devDependencies": {
    "aws-sdk": "^2.6.4",
    "axios": "^0.14.0",
    "babel-preset-es2015-rollup": "^1.1.1",
    "babel-preset-react": "^6.5.0",
    "hellojs": "^1.14.0",
    "jquery": "^2.2.4",
    "livereload": "^0.5.0",
    "npm-run-all": "^3.1.0",
    "opener": "^1.4.2",
    "react": "^15.1.0",
    "react-bootstrap": "^0.30.3",
    "react-dom": "^15.1.0",
    "react-redux": "^3.1.2",
    "react-router": "^2.8.1",
    "react-router-redux": "^4.0.5",
    "redux": "^3.5.2",
    "redux-logger": "^2.0.5",
    "redux-thunk": "^1.0.3",
    "remarkable": "^1.6.2",
    "rest-api": "file:///C:\\Projects\\cloud-iris-rest-api\\rest-api",
    "rollup": "^0.36.0",
    "rollup-plugin-babel": "^2.4.0",
    "rollup-plugin-commonjs": "^4.1.0",
    "rollup-plugin-json": "^2.0.2",
    "rollup-plugin-jsx": "^1.0.3",
    "rollup-plugin-node-builtins": "^1.1.0",
    "rollup-plugin-node-globals": "^1.0.9",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-replace": "^1.1.0",
    "rollup-plugin-sass": "^0.2.0",
    "rollup-plugin-typescript": "^0.7.5",
    "rollup-plugin-uglify": "^0.3.1",
    "tslint": "^3.15.1",
    "typings": "^1.0.4",
    "watch": "^0.19.2"
  }
}
```

If you can't reproduce, I'll try to create a smaller test case.

**Comment by calvinmetcalf** [comment]
I can reproduce

**Comment by calvinmetcalf** [comment]
this would be the line 

```js
if (typeof process === 'undefined') {
  process = {
    browser: true
  };
}
```

though I doubt the aws sdk will work as it requires browserify-crypto and I know for a fact (having tested that one and also authored it) that it won't work with rollup

**Comment by TheBosZ** [comment]
Darn that sucks. What's the reason crypto won't work?

**Comment by calvinmetcalf** [comment]
it has a lot of deps and some of them include circular dependencies that are incompatibly with es6 modules,  what you could do is try bundling the aws-sdk with browserify and then using that with rollup

**Comment by TheBosZ** [comment]
If the problem is just the crypto library, you can close this. I ended up browserify-ing the library and then using it as an external resource in rollup.

**Comment by calvinmetcalf** [comment]
yeah crypto-browserify is sort of a prefect stress test for rollup as it has certain parts that people use very often (randomBytes and hashes/hmacs) but others that are used very rarely but have a lot of baggage (like the asymmetrical encryption stuff), currency rollup doesn't really handle tree shaking the asymmetrical stuff (and the associated elliptical curve and big number stuff) right now, but I may port a sane subset of it to ES6

**Comment by TheBosZ** [comment]
I wonder if it would make sense to use something like CryptoJS instead of trying to get node crypto to work.

Possibly we could implement a polyfill that exposes CryptoJS using the same API as node crypto.

**Comment by calvinmetcalf** [comment]
> Possibly we could implement a polyfill that exposes CryptoJS using the same API as node crypto.

browserify crypto is basically what you just described but modulearized so you can require parts of it without getting all of it,
